name: server check

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'buildSrc/**'
      - 'protos/**'
      - 'gradle/**'
      - 'libs/**'
      - 'connectors/**'
      - 'stub/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/server-check.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
      - 'buildSrc/**'
      - 'protos/**'
      - 'gradle/**'
      - 'libs/**'
      - 'connectors/**'
      - 'stub/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/server-check.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false

      - name: Check
        run: nix develop --command gradle check
        env:
          GRADLE_TOKEN: ${{ secrets.GRADLE_TOKEN }}
