name: server check

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'buildSrc/**'
      - 'protos/**'
      - 'gradle/**'
      - 'libs/**'
      - 'connectors/**'
      - 'stub/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/server-check.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
      - 'buildSrc/**'
      - 'protos/**'
      - 'gradle/**'
      - 'libs/**'
      - 'connectors/**'
      - 'stub/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/server-check.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Check
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: check
        env:
          GRADLE_TOKEN: ${{ secrets.GRADLE_TOKEN }}
